In [96]:
import pandas as pd
import scipy.sparse as sp
import numpy as np
import json
import torch

In [97]:
from sklearn.metrics.pairwise import cosine_similarity

def get_similar_keyphrases(input, m_kav_mean):    
    cs = cosine_similarity(m_kav_mean[input].reshape(1, -1),m_kav_mean)[0]
    cands = cs.argsort()[::-1][1:6]
    return cands

def get_similar_keyphrases_movies(input, m_kav_mean, m_items):
    cs = cosine_similarity(m_kav_mean[input].reshape(1, -1),m_items)[0]
    cands = cs.argsort()[::-1][:5]
    return cands


In [98]:
df_tags = pd.read_csv('./data/yelp/fold0/tr_tags.csv')

rows, cols = df_tags.item, df_tags.tag
values = np.ones(len(df_tags))

m_item_keyphrase= sp.csr_matrix((values, (rows, cols)), dtype='float64')

In [99]:
with open('./data/yelp/tag_id_dict.json') as f:
    tag_id_dict = json.load(f)
with open('./data/yelp/id_business_dict.json') as f:
    id_business_dict = json.load(f)

id_tag_dict = {id: tag for tag, id in tag_id_dict.items()}
id_business_dict = {int(id): b for id, b in id_business_dict.items()}

In [5]:
a

NameError: name 'a' is not defined

In [100]:
PATH = './saves/yelp/VAE_beta_multilayer.pt'
model = torch.load(PATH, map_location=torch.device('cpu'))
item_embeddings = model.decoder.weight.detach().numpy()
item_bias = model.decoder.bias.detach().numpy()

In [6]:
np.quantile(item_bias,0.01)

0.07911904633045197

In [7]:
item_embeddings.shape

(4997, 100)

In [116]:
from utils.KAVgenerator import KAVgenerator
k = KAVgenerator(m_item_keyphrase,item_embeddings, 20)
keyphrase_embeddings = k.get_all_mean_kav(20, 100)

100%|██████████| 245/245 [00:18<00:00, 13.28it/s](245, 100, 100)



In [117]:
np.mean(np.linalg.norm(item_embeddings, ord=2, axis=1, keepdims=True))

0.6559366

In [118]:
np.mean(np.linalg.norm(keyphrase_embeddings, ord=2, axis=1, keepdims=True))

0.5629330642634401

In [119]:
id_tag_dict 

{0: 'tea',
 1: 'parking',
 2: 'cookie',
 3: 'milk',
 4: 'quick',
 5: 'pricey',
 6: 'bar',
 7: 'coffee',
 8: 'green tea',
 9: 'convenient',
 10: 'fancy',
 11: 'chocolate',
 12: 'banana',
 13: 'lemon',
 14: 'milk tea',
 15: 'busy',
 16: 'fresh',
 17: 'friendly',
 18: 'quiet',
 19: 'music',
 20: 'chip',
 21: 'baked',
 22: 'ambiance',
 23: 'sandwich',
 24: 'latte',
 25: 'window',
 26: 'cozy',
 27: 'decent price',
 28: 'flavorful',
 29: 'coconut',
 30: 'fried',
 31: 'fish',
 32: 'fry',
 33: 'shrimp',
 34: 'scallop',
 35: 'calamari',
 36: 'dark',
 37: 'deep fried',
 38: 'efficient',
 39: 'classic',
 40: 'taco',
 41: 'lettuce',
 42: 'corn',
 43: 'tomato',
 44: 'fair',
 45: 'sour',
 46: 'soup',
 47: 'salad',
 48: 'crispy',
 49: 'seafood',
 50: 'meat',
 51: 'lobster',
 52: 'bun',
 53: 'mayo',
 54: 'salt',
 55: 'juicy',
 56: 'fast',
 57: 'wait',
 58: 'stuffed',
 59: 'yummy',
 60: 'cake',
 61: 'squid',
 62: 'ice cream',
 63: 'clean',
 64: 'juice',
 65: 'honey',
 66: 'smooth',
 67: 'stick',
 68: '

In [120]:
outputs = []

In [121]:
id = tag_id_dict['tea']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['tea'] + output)

['milk', 'milk tea', 'bubble', 'noodle', 'soup']


In [122]:
id = tag_id_dict['cheesecake']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['cheesecake'] + output)

['cake', 'wing', 'lobster', 'dessert', 'dim sum']


In [123]:
id = tag_id_dict['burger']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['burger'] + output)

['fry', 'breakfast', 'pizza', 'pasta', 'juicy']


In [124]:
id = tag_id_dict['taco']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['taco'] + output)

['cocktail', 'chip', 'bread', 'octopus', 'mexican']


In [125]:
id = tag_id_dict['italian']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['italian'] + output)

['pasta', 'pizza', 'fresh', 'friendly', 'tomato']


In [126]:
id = tag_id_dict['sandwich']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['sandwich'] + output)

['friendly', 'coffee', 'latte', 'cocktail', 'spicy']


In [127]:
id = tag_id_dict['japanese']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['japanese'] + output)

['salmon', 'miso', 'creamy', 'green tea', 'fish']


In [128]:
id = tag_id_dict['parking']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)

['fresh', 'crispy', 'markham', 'store', 'sesame']


In [129]:
id = tag_id_dict['spicy']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['spicy'] + output)

['friendly', 'meat', 'fish', 'tuna', 'fresh']


In [130]:
id = tag_id_dict['ramen']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['ramen'] + output)

['soup', 'noodle', 'bubble', 'dim sum', 'bubble tea']


In [131]:
id = tag_id_dict['vegetarian']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['vegetarian'] + output)

['vegan', 'wrap', 'coffee', 'cozy', 'brunch']


In [132]:
id = tag_id_dict['healthy']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['healthy'] + output)

['salad', 'coffee', 'cake', 'potato', 'chocolate']


In [133]:
id = tag_id_dict['french']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['french'] + output)

['bread', 'brunch', 'olive', 'toast', 'wine']


In [134]:
id = tag_id_dict['cheap']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['cheap'] + output)

['takeout', 'pork', 'noodle', 'pot', 'spring roll']


In [135]:
id = tag_id_dict['seafood']
cands = get_similar_keyphrases(id, keyphrase_embeddings)
output = []
for kp in cands:
    output.append(id_tag_dict[kp])
print(output)
outputs.append(['seafood'] + output)

['meat', 'pricey', 'mayo', 'fresh', 'modern']


In [136]:
df = pd.DataFrame(outputs).set_index(0)
df.index.name = None
df

1          2        3          4            5
tea             milk   milk tea   bubble     noodle         soup
cheesecake      cake       wing  lobster    dessert      dim sum
burger           fry  breakfast    pizza      pasta        juicy
taco        cocktail       chip    bread    octopus      mexican
italian        pasta      pizza    fresh   friendly       tomato
sandwich    friendly     coffee    latte   cocktail        spicy
japanese      salmon       miso   creamy  green tea         fish
spicy       friendly       meat     fish       tuna        fresh
ramen           soup     noodle   bubble    dim sum   bubble tea
vegetarian     vegan       wrap   coffee       cozy       brunch
healthy        salad     coffee     cake     potato    chocolate
french         bread     brunch    olive      toast         wine
cheap        takeout       pork   noodle        pot  spring roll
seafood         meat     pricey     mayo      fresh       modern

In [137]:
from utils.Dataset import Dataset
dataset = Dataset(data_dir='./data/yelp/fold0/',load_keyphrases=True)

Read data from ./data/yelp/fold0/


In [138]:
def get_user_info(user_id, input_matrix):
    user_input = input_matrix[user_id]
    nonzeros = user_input.nonzero()
    items = nonzeros[1]
    ratings = user_input[nonzeros]
    ratings = np.asarray(ratings).reshape(-1)
    sorted_ratings_idx = ratings.argsort()[::-1]
    sorted_items = items[sorted_ratings_idx]
    sorted_ratings = ratings[sorted_ratings_idx]
    return sorted_items, sorted_ratings

def get_user_preds(user_id, input_matrix):
    user_input = input_matrix[user_id]
    mask_index = user_input.nonzero()[1]
    i = torch.FloatTensor(user_input.toarray()).to(torch.device('cpu'))
    with torch.no_grad():
        preds = model.forward(i).cpu().numpy()
    preds = np.asarray(preds).reshape(-1)
    preds[mask_index] = -np.inf
    sorted_pred_items = preds.argsort()[::-1]
    sorted_pred_ratings = preds[sorted_pred_items] 
    return sorted_pred_items, sorted_pred_ratings

def get_mu_cov(user_id, input_matrix, moddel):
    user_input = input_matrix[user_id]
    i = torch.FloatTensor(user_input.toarray()).to(torch.device('cpu'))
    with torch.no_grad():
        mu, logvar = model.get_mu_logvar(i)
    std = model.logvar2std(logvar)
    mu, std = mu.numpy().T, std.numpy()

    return mu, np.diagflat(std*std)

def get_user_preds_using_mu(user_mu, input_matrix, model):
    user_input = input_matrix[user_id]
    mask_index = user_input.nonzero()[1]
    _mu = torch.FloatTensor(user_mu.T)

    with torch.no_grad():
        preds = model.decoder(_mu)
    preds = np.asarray(preds).reshape(-1)
    preds[mask_index] = -np.inf
    sorted_pred_items = preds.argsort()[::-1]
    sorted_pred_ratings = preds[sorted_pred_items] 
    return sorted_pred_items, sorted_pred_ratings

def update_posterior(x, y, S_0, m_0, prec_y):
    S_0_inv = np.linalg.inv(S_0)
    #S_1 = np.linalg.inv(S_0_inv +prec_y * x @ x.T)    
    #print(np.swapaxes(x,-2,-1).shape)
    S_1 = np.linalg.inv(S_0_inv +prec_y * np.matmul(x,np.swapaxes(x,-2,-1)))
    m_1 = S_1 @ (S_0_inv @ m_0 + prec_y * y * x)
    #print(m_1.shape)
    return S_1, m_1


In [139]:
outputs = []
dataset.train_matrix.shape


(7000, 4997)

In [563]:
user_id = 351
sorted_items, sorted_ratings = get_user_info(user_id, dataset.train_matrix)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_business_dict[item_id])
print(output)
outputs.append(['user history'] + output)

sorted_items, sorted_ratings = get_user_preds(user_id, dataset.train_matrix)
top10_items = sorted_items[:330]
output = []

for item_id in top10_items:
    output.append(id_business_dict[item_id])
print(output)
outputs.append(['initial recs'] + output)
mu, cov = get_mu_cov(user_id, dataset.train_matrix, model)


['Gandhi Cuisine', 'Sansotei', 'Naniwa-Taro', 'Athens Pastries', 'One2 Snacks', 'Ghazale', 'Pho Linh', 'Von Doughnuts', 'Stop BBQ Chicken', 'Pho Metro']
['Fahrenheit Coffee', 'New Toronto Fish & Chips', 'Golden Dough', "I'll Be Seeing You", 'Shalom Ethopian Restaurant', "The Captain's Boil", 'Noble Coffee', 'Southeast Sandwiches', 'Veghed', 'New Orleans Seafood & Steakhouse', 'Yasu', 'Golden Gecko Coffee', 'Big Cannoli Lane', 'The Alternative Cafe', 'San Antonio Seafood Market', 'Hooked', 'Grill Gate', 'Harvest Green', 'Famiglia Baldassarre', 'The Dumpling Shop', 'Village Juicery', 'Baretto Caffe', 'Pestacio', "Scheffler's Delicatessen", 'Cobs Bread', 'Oakwood Espresso', "Yan's Soy Foods", 'Food Dudes Pantry', 'Porta Via Restaurant & Catering', 'La Cubana', 'De La Mer', 'Kekou Gelato House', "Mother's Deli & Bakery", 'Cakes By Robert', 'Cinnabon', 'Oca Nera', "Taro's Fish", 'Amma Roti House', 'Kristapsons', 'Pascale Gourmet', 'Crimson Teas', 'Alo Restaurant', 'La Salumeria', 'Mr. Chest

In [324]:
sorted_ratings[1]

4.8263574

In [530]:
seafood = tag_id_dict['chip']

In [531]:
mu.T@keyphrase_embeddings[seafood][:,np.newaxis]

array([[1.15784721]])

In [532]:
np.quantile(mu.T@(keyphrase_embeddings.T),q=0.01)

-2.022886229791352

In [533]:
np.quantile(mu.T@(item_embeddings.T),q=0.1)

2.41802716255188

In [534]:
item_embeddings.shape

(4997, 100)

In [535]:
prec = np.linalg.norm(1/(cov+1e-6))
neg = np.min(mu.T @ keyphrase_embeddings.T)
pos = np.max(mu.T @ keyphrase_embeddings.T)
print(pos, neg)

3.2033172233684457 -2.282314772954342


In [536]:
prec

99498770.0

In [546]:
x = keyphrase_embeddings[seafood][:,np.newaxis]
y = [[neg]]

cov1, mu1 = update_posterior(x, y, cov, mu, np.array(1))

In [547]:
mu1.T@keyphrase_embeddings[seafood][:,np.newaxis]

array([[0.81489264]])

In [548]:
sorted_items, sorted_ratings = get_user_preds_using_mu(mu1, dataset.train_matrix, model)
top10_items = sorted_items[:50]
output = []
for item_id in top10_items:
    output.append(id_business_dict[item_id])
print(output)
outputs.append(['+ franch'] + output)

['Fahrenheit Coffee', 'Golden Dough', "The Captain's Boil", 'New Toronto Fish & Chips', "I'll Be Seeing You", 'Shalom Ethopian Restaurant', 'Noble Coffee', 'Southeast Sandwiches', 'Yasu', 'Veghed', 'Big Cannoli Lane', "Yan's Soy Foods", 'The Dumpling Shop', 'Famiglia Baldassarre', 'Golden Gecko Coffee', 'Pestacio', 'New Orleans Seafood & Steakhouse', 'Baretto Caffe', 'Grill Gate', 'Harvest Green', 'San Antonio Seafood Market', 'The Alternative Cafe', 'Cobs Bread', 'Village Juicery', 'Hooked', "Mother's Deli & Bakery", 'Oakwood Espresso', "Scheffler's Delicatessen", 'Porta Via Restaurant & Catering', 'Kekou Gelato House', 'Amma Roti House', 'Oca Nera', "Taro's Fish", 'Food Dudes Pantry', 'De La Mer', 'Kristapsons', 'Cinnabon', 'Cakes By Robert', 'Mr. Chestnut', 'La Cubana', 'Mississauga Rotary Ribfest', 'Alo Restaurant', 'Nguyên Huong', 'Pascale Gourmet', 'Crimson Teas', 'DAVIDsTEA', 'Viva Shawarma', 'Green Box Express', 'Starbucks', "Dante's Inferno Paninoteca"]


In [551]:
seafood = tag_id_dict['dessert']
x = keyphrase_embeddings[seafood][:,np.newaxis]
y = [[pos]]

cov2, mu2 = update_posterior(x, y, cov1, mu1, np.array(1000))

sorted_items, sorted_ratings = get_user_preds_using_mu(mu2, dataset.train_matrix, model)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_business_dict[item_id])
print(output)
outputs.append(['- japanese'] + output)

["Yan's Soy Foods", 'Mr. Chestnut', "Allan's Pastry Shop", 'Yasu', 'Grande Cheese', 'The Dumpling Shop', 'Lox + Schmear', 'Fahrenheit Coffee', "Taro's Fish", 'Bodira Cafe and Fine Foods']


In [125]:
df = pd.DataFrame(outputs).set_index(0)
df.index.name = None
df

1                         2   \
user history        C & Dubbs Hamburgers  Village Ice Cream Shoppe   
initial recs  San Antonio Seafood Market            Porchetta Roll   
+ japanese                          Yasu         The Dumpling Shop   
- japanese    San Antonio Seafood Market      Rose's Halal Kitchen   

                            3                             4   \
user history     Baretto Caffe           The Burger's Priest   
initial recs  Oakwood Espresso  Ruby's Mediterranean Cuisine   
+ japanese             Katsuya          Famiglia Baldassarre   
- japanese          Patty Time                     The Manna   

                                      5                             6   \
user history  Mississauga Rotary Ribfest           Earls Kitchen + Bar   
initial recs                        Yasu          Rose's Halal Kitchen   
+ japanese              Loukoumania Café  Ruby's Mediterranean Cuisine   
- japanese                Porchetta Roll              Gale's Snack Bar   

                                            7                 8   \
user history  New Orleans Seafood & Steakhouse          Pho Hung   
initial recs                    Lickadee Split          Pestacio   
+ japanese                    Oakwood Espresso    Porchetta Roll   
- japanese                            Pestacio  Oakwood Espresso   

                            9                   10  
user history        Primo Veal  The Goose & Firkin  
initial recs  Adamson Barbecue   The Dumpling Shop  
+ japanese         Taro's Fish    Adamson Barbecue  
- japanese       Viva Shawarma        Karahi Point

In [71]:
outputs = []

In [72]:
user_id = 300
sorted_items, sorted_ratings = get_user_info(user_id, dataset.train_matrix)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id][:-7])

outputs.append(['user history'] + output)
print(output)

sorted_items, sorted_ratings = get_user_preds(user_id, dataset.train_matrix)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id][:-7])
outputs.append(['initial recs'] + output)
print(output)

mu, cov = get_mu_cov(user_id, dataset.train_matrix, model)
prec = np.linalg.norm(1/(cov+1e-6))

prec = np.linalg.norm(1/(cov+1e-6))
neg = np.min(mu.T @ keyphrase_embeddings.T)
pos = np.max(mu.T @ keyphrase_embeddings.T)
print(pos, neg)

['Pulp Fiction', 'Battleship Potemkin, The (Bronenosets Potyomkin)', 'Woman Under the Influence, A', 'Apocalypse Now', 'Seven Samurai (Shichinin no samurai)', 'Wings of Desire (Der Himmel über Berlin)', 'Son, The (Le Fils)', 'Stroszek', 'Rio Bravo', 'Wallace & Gromit: The Curse of the Were-Rabbit']
['Pier, The (La Jetée)', '2001: A Space Odyssey', '8 1/2', 'Sunrise: A Song of Two Humans', 'Andrei Rublev (Andrey Rublyov)', 'Gerry', 'Paranoid Park', 'Wild Bunch, The', 'Red River', 'Cyclo (Xich lo)']
2.684969023457633 -2.7016516940258937


In [79]:
x = keyphrase_embeddings[18][:,np.newaxis]
y = [[pos]]

cov1, mu1 = update_posterior(x, y, cov, mu, np.array(1))

sorted_items, sorted_ratings = get_user_preds_using_mu(mu1, dataset.train_matrix, model)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id][:-7])
outputs.append(['+ fantasy'] + output)
print(output)



['Pier, The (La Jetée)', '2001: A Space Odyssey', '8 1/2', 'Sunrise: A Song of Two Humans', 'Andrei Rublev (Andrey Rublyov)', 'Gerry', 'Paranoid Park', 'Wild Bunch, The', 'Red River', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb']


In [81]:
x = keyphrase_embeddings[18][:,np.newaxis]
y = [[neg]]

cov1, mu1 = update_posterior(x, y, cov, mu, np.array(10))

sorted_items, sorted_ratings = get_user_preds_using_mu(mu1, dataset.train_matrix, model)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id][:-7])
outputs.append(['- fantasy'] + output)
print(output)



['Pier, The (La Jetée)', 'Sunrise: A Song of Two Humans', 'Sorrow and the Pity, The (Chagrin et la pitié, Le)', 'Gerry', '2001: A Space Odyssey', 'Paranoid Park', 'Andrei Rublev (Andrey Rublyov)', '8 1/2', 'Au Hasard Balthazar', 'Fat City']


In [283]:
df = pd.DataFrame(outputs).set_index(0)
df.index.name = None
df

1   \
user history           Pulp Fiction   
initial recs   Pier, The (La Jetée)   
+ fantasy     2001: A Space Odyssey   
- fantasy      Pier, The (La Jetée)   

                                                            2   \
user history  Battleship Potemkin, The (Bronenosets Potyomkin)   
initial recs                             2001: A Space Odyssey   
+ fantasy                                 Pier, The (La Jetée)   
- fantasy                        Sunrise: A Song of Two Humans   

                                        3   \
user history  Woman Under the Influence, A   
initial recs                         8 1/2   
+ fantasy                            8 1/2   
- fantasy            2001: A Space Odyssey   

                                                             4   \
user history                                     Apocalypse Now   
initial recs                      Sunrise: A Song of Two Humans   
+ fantasy     Dr. Strangelove or: How I Learned to Stop Worr...   
- fantasy                                                 8 1/2   

                                                5   \
user history  Seven Samurai (Shichinin no samurai)   
initial recs        Andrei Rublev (Andrey Rublyov)   
+ fantasy                          Wild Bunch, The   
- fantasy                                    Gerry   

                                                    6                   7   \
user history  Wings of Desire (Der Himmel über Berlin)  Son, The (Le Fils)   
initial recs                                     Gerry       Paranoid Park   
+ fantasy                                Touch of Evil           Chinatown   
- fantasy               Andrei Rublev (Andrey Rublyov)       Paranoid Park   

                                                             8   \
user history                                           Stroszek   
initial recs                                    Wild Bunch, The   
+ fantasy                                           City Lights   
- fantasy     Sorrow and the Pity, The (Chagrin et la pitié,...   

                                                       9   \
user history                                    Rio Bravo   
initial recs                                    Red River   
+ fantasy     Beauty and the Beast (Belle et la bête, La)   
- fantasy                                        Fat City   

                                                          10  
user history  Wallace & Gromit: The Curse of the Were-Rabbit  
initial recs                                 Cyclo (Xich lo)  
+ fantasy                     Andrei Rublev (Andrey Rublyov)  
- fantasy                                Au Hasard Balthazar

In [274]:
mu.T@keyphrase_embeddings[18][:,np.newaxis]

array([[-0.59178778]])

In [124]:
x = keyphrase_embeddings[37][:,np.newaxis]
y = [[2]]

cov2, mu2 = update_posterior(x, y, cov1, mu1, np.array(np.linalg.norm(1/(cov1+1e-6))))
sorted_items, sorted_ratings = get_user_preds_using_mu(mu2, dataset.train_matrix, model)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id])
print(output)



['Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)', 'City Lights (1931)', 'Chinatown (1974)', '2001: A Space Odyssey (1968)', 'Godfather, The (1972)', 'Maltese Falcon, The (1941)', 'Annie Hall (1977)', 'Godfather: Part II, The (1974)', 'Double Indemnity (1944)', 'Treasure of the Sierra Madre, The (1948)']


In [405]:
user_id = 77
sorted_items, sorted_ratings = get_user_info(user_id, dataset.train_matrix)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id])
print(output)

sorted_items, sorted_ratings = get_user_preds(user_id, dataset.train_matrix)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id])
print(output)

mu, cov = get_mu_cov(user_id, dataset.train_matrix, model)


['Pulp Fiction (1994)', 'Star Trek II: The Wrath of Khan (1982)', '8 1/2 (1963)', 'Sling Blade (1996)', 'Dogma (1999)', 'Fight Club (1999)', 'Third Man, The (1949)', 'Lord of the Rings: The Fellowship of the Ring, The (2001)', 'Boat, The (Das Boot) (1981)', 'Fanny and Alexander (Fanny och Alexander) (1982)']
['Godfather, The (1972)', 'Memento (2000)', 'Usual Suspects, The (1995)', 'Face in the Crowd, A (1957)', 'Saving Private Ryan (1998)', 'Mongol (2007)', 'Bad Santa (2003)', 'Terminator 2: Judgment Day (1991)', 'Curious Case of Benjamin Button, The (2008)', 'Aliens (1986)']


In [421]:
x = keyphrase_embeddings[19][:,np.newaxis]
y = [[5.]]

cov1, mu1 = update_posterior(x, y, cov, mu, np.array(100))
cov1
sorted_items, sorted_ratings = get_user_preds_using_mu(mu1, dataset.train_matrix, model)
top10_items = sorted_items[:10]
output = []
for item_id in top10_items:
    output.append(id_title_dict[item_id])
print(output)



['Usual Suspects, The (1995)', 'Memento (2000)', 'Terminator 2: Judgment Day (1991)', 'Aliens (1986)', 'Saving Private Ryan (1998)', 'Godfather, The (1972)', 'X2: X-Men United (2003)', 'Gattaca (1997)', 'Spider-Man 2 (2004)', 'Monty Python and the Holy Grail (1975)']


In [54]:
id_tag_dict

{0: 'anime',
 1: 'super-hero',
 2: 'woody allen',
 3: 'comic book',
 4: 'samuel l jackson',
 5: 'brad pitt',
 6: 'bruce willis',
 7: 'time travel',
 8: 'crime',
 9: 'serial killer',
 10: 'action',
 11: 'jim carrey',
 12: 'stupid',
 13: 'dystopia',
 14: 'drama',
 15: 'aliens',
 16: 'based on a book',
 17: 'classic',
 18: 'fantasy',
 19: 'sci-fi',
 20: 'space',
 21: 'arnold schwarzenegger',
 22: 'matt damon',
 23: 'oscar (best actor)',
 24: 'oscar (best picture)',
 25: 'ghosts',
 26: 'twist ending',
 27: 'stephen king',
 28: 'tom hanks',
 29: 'interesting',
 30: 'dvd',
 31: 'nicolas cage',
 32: 'magic',
 33: 'morgan freeman',
 34: 'bond',
 35: 'music',
 36: 'gay',
 37: 'comedy',
 38: 'funny',
 39: 'alfred hitchcock',
 40: 'true story',
 41: 'family',
 42: 'film noir',
 43: 'heist',
 44: 'quirky',
 45: 'sequel',
 46: 'memory',
 47: 'psychology',
 48: 'espionage',
 49: 'satire',
 50: 'shakespeare',
 51: 'black comedy',
 52: 'adventure',
 53: 'girlie movie',
 54: 'teen',
 55: 'disney',
 56:

In [154]:
model.logvar2std(logvar)

tensor([[0.6065, 0.6066, 0.6065, 0.6909, 0.6065, 1.0357, 0.6321, 0.7306, 0.8367,
         0.9005, 0.6890, 0.6065, 0.6202, 0.6615, 0.6069, 0.6066, 0.7204, 0.6065,
         0.8023, 0.6065, 0.6065, 0.6065, 0.7750, 0.6070, 0.6065, 0.6065, 0.6066,
         0.6558, 1.0224, 0.6065, 0.6390, 0.7475, 0.6065, 0.6097, 0.6065, 0.6976,
         0.6065, 0.7138, 0.9611, 0.6307, 0.6065, 0.6065, 0.6065, 0.6065, 0.7756,
         0.6185, 0.6075, 0.6081, 0.6065, 0.6065]])

In [78]:
sorted_ratings = ratings.argsort()[::-1]
sorted_items = items[sorted_ratings]
sorted_items

array([1782, 4270, 3084, ..., 1858, 2873, 7813], dtype=int32)

In [76]:
arr1inds

array([1115, 2345, 1815, ..., 1158, 1709, 3787])

In [77]:
ratings[arr1inds]

array([5., 5., 5., ..., 1., 1., 1.])

In [171]:
a =np.random.normal(np.zeros(150),0.01)
a = a[:,np.newaxis]

In [176]:
np.quantile(a.T@(keyphrase_embeddings.T),q=0.99)

0.013279970142235526

In [165]:
np.random.normal(np.zeros(50),0.001)

array([ 0.00175503, -0.0018365 , -0.00092557, -0.0013183 ,  0.00070177,
       -0.00045205, -0.00063023,  0.00231926,  0.00274795, -0.00030118,
       -0.00102944,  0.00221119, -0.00020627,  0.00062257,  0.00136277,
        0.00194146, -0.00048117, -0.00046926,  0.00112981, -0.00067896,
        0.00059334,  0.00093145, -0.00020276, -0.00019905, -0.00110767,
        0.00229955,  0.00026535, -0.00072867, -0.00150996, -0.00102973,
        0.00242328,  0.00081131,  0.00183528, -0.00051625, -0.00056769,
       -0.00143513,  0.00020218, -0.00069088, -0.00053919,  0.00166264,
        0.00039374,  0.00120685, -0.0008378 ,  0.00058671, -0.00062085,
       -0.00133637,  0.00044003,  0.0004339 , -0.00023481, -0.00046481])

In [184]:
a = np.zeros((150,150), int)
np.fill_diagonal(a, 1)

np.linalg.norm(a)

12.24744871391589

In [190]:
def get_predictive_dist(x_pred, S, m, prec_y):
    print(m.T)
    pred_means = m.T @ x_pred
    pred_means = pred_means.flatten()
    pred_vars = np.sum(1/prec_y + x_pred.T @ S * x_pred.T, axis=1)

    return pred_vars, pred_means

In [194]:
x_pred = np.array([[1,2,3],[2,3,4]]).T
S = np.array([[1,1,1],[1,1,1],[1,1,1]])
m = np.array([[1],[2],[3]])
get_predictive_dist(x_pred, S, m, 1)



[[1 2 3]]


(array([39., 84.]), array([14, 20]))

In [198]:
np.array([1,2,3]) == 1

array([ True, False, False])

In [197]:
np.array(np.linalg.norm(1/(S+1e-6)))**2

8.999982000027002